site_name: 3DPrinter.Voron
site_url: https://Hecatron-Cad.github.io/3DPrinter.Voron
repo_name: Hecatron-Cad/3DPrinter.Voron
repo_url: https://github.com/Hecatron-Cad/3DPrinter.Voron.git

site_description: >-
  Documentation for the setup of my Voron 2.4 350 printer
copyright: Copyright &copy; 2024 - 2024

docs_dir: ./content/
theme:
  name: material
  features:
    - navigation.indexes 
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - announce.dismiss
    #- content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
#  font:
#    text: Roboto
#    code: Roboto Mono

  font:
    text: SpaceGrotesk
    code: SpaceMono

  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - awesome-pages
  - search
  - glightbox
  - mkdocs-video
  - tags
  - git-revision-date-localized
  - autorefs

#  - mkdocstrings:
#      handlers:
#        python:
#          paths: [..]
#          options:
#            show_root_heading: true
#            show_symbol_type_heading: true
#            show_symbol_type_toc: true
#            show_bases: false
#            show_signature_annotations: true
#            merge_init_into_class: true
#            summary: true

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: wavedrom
          class: language-wavedrom
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  # used by wavedrom plugin
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.5.0/wavedrom.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.5.0/skins/default.js

    # HighlightJS for coloring in code blocks - https://highlightjs.org/static/demo/
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js
  - assets/js/hljs/config.js

    # Sortable tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - assets/js/sorttable/config.js

extra_css:
    # HighlightJS for coloring in code blocks - https://highlightjs.org/static/demo/
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/atelier-dune-light.min.css
  - stylesheets/extra.css
